### ISSUE TITLE
Adjustments for hackathon

### ISSUE THREAD

**Issue by moritzfelipe** [dacadeorg/dacade-frontend-app#1084]
### Tasks
- [ ] Hint is not shown ("hint": "Don’t have a team member in Central Europe? Join the ICP Central Europe Telegram group to find teammates! (LINK)")
- [ ] Deadline Missing( Mar 18, 8:00 AM GMT+1)
- [ ] Team formation for missing 
![Image](https://github.com/dacadeorg/dacade-frontend-app/assets/1242997/5ed2e30a-44c7-4f32-9279-bc788158d222)
Start now should lead to telegram and message should reflect that (https://t.me/+0oJye8IwAuxkMDY0) "Open telegram and find your teammates")
- [ ] Team formation should link to telegram instead of discord
- [ ] "You need to get 90% to get into the prize pool and earn prizes worth of USD 7,000." This line should say 70% for 10.000 USD
- [ ] Token should be ICP in USD.
