### ISSUE TITLE
Team challenge bugs

### ISSUE THREAD

**Issue by serapieTuyishime** [dacadeorg/dacade-frontend-app#922]
```[tasklist]
### Tasks
- [ ] Team limit should come from the backend
- [x] Add the correct discord channel to find teams. It should be this one (https://discord.gg/HDsN3jgyg2)
- [x] Provide visuals when the user accepts or rejects the invitation
- [ ] Admin doesn't see the username if they enter it, they need to refresh to see if someone accepted, or the admin needs to delete them. This should not be because they should enter the name and see the correct user.
- [x] Invite is going away in the notifications before people can click on them
- [x] Invite cannot be accepted on the challenge page.
- [x] The currently logged-in user is displayed as the organizer of the team when you view the submission.
- [x] Add all members to the best submissions card too
```
